name: CI/CD for ML Model on Minikube

on:
  push:
    branches:
      - main

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up Minikube
      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.8.0
        with:
          minikube_version: 'latest'   # Corrected from 'minikube-version' to 'minikube_version'
          kubernetes_version: 'latest' # Corrected from 'kubernetes-version' to 'kubernetes_version'
          driver: docker

      # Step 2: Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Step 3: Set up Docker for Minikube
      - name: Use Minikube Docker environment
        run: |
          eval $(minikube docker-env)

      # Step 4: Build Docker image
      - name: Build Docker image in Minikube
        run: |
          docker build -t ml-model:latest .

      # Step 5: Apply Kubernetes manifests
      - name: Deploy application to Minikube
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      # Step 6: Verify deployment
      - name: Wait for pods to be ready
        run: |
          kubectl wait --for=condition=ready pod -l app=ml-model --timeout=120s
